export { default as Additional } from "./Additional";
export { default as Education } from "./Education";
export { default as Experience } from "./Experience";
export { default as Header } from "./Header";
export { default as Languages } from "./Languages";
export { default as Profile } from "./Profile";
export { default as Projects } from "./Projects";
export { default as Social } from "./Social";
export { default as Tech } from "./Tech";
